import notions_convexity_relation_several_complex_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace notions_convexity_relation_several_complex_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end notions_convexity_relation_several_complex_theorem_canonical_lane_mathlib
end HautevilleHouse
